version: "3.9"

services:
  auth_service:
    container_name: auth_service
    build: ./auth_service
    ports:
      - "5007:5007"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./auth_service:/app
    networks:
      - shared_net

  mcp_service:
    container_name: mcp_service
    build: ./mcp_service
    ports:
      - "8787:8787"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./mcp_service:/app
      - ./LLM_service:/home/ahmedetsh/Desktop/LLM_MCP/LLM_service
    networks:
      - shared_net

  nginx:
    image: nginx:latest
    container_name: llm_mcp-nginx-1
    ports:
      - "443:443"
    volumes:
      - ./auth_service/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./auth_service/nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./auth_service/certs:/etc/nginx/certs:ro
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - auth_service
      - mcp_service
      - prometheus
      - grafana
    networks:
      - shared_net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - shared_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./monitoring/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    name: llm_mcp_shared_net

